// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Account = {
  id?: string;
  createdOn?: string;
  active?: boolean;
  email?: string;
  emailVerified?: boolean;
  password?: string;
  passwordAge?: number;
  name?: string;
  nickname?: string;
  nicknameChangeTimeout?: number;
  picture?: string;
  locale?: string;
  birthday?: string;
  country?: string;
}

