// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type SecurityEvent = {
  sessionClosed?: SecurityEvent_SessionClosed;
  tokenRevoked?: SecurityEvent_TokenRevoked;
  accountPurged?: SecurityEvent_AccountPurged;
}

export type SecurityEvent_SessionClosed = {
  issuer?: string;
  subject?: string;
  sessionId?: string;
}

export type SecurityEvent_TokenRevoked = {
  issuer?: string;
  subject?: string;
  tokenType?: string;
  tokenHashMd5?: string;
}

export type SecurityEvent_AccountPurged = {
  issuer?: string;
  subject?: string;
}

