"use strict";
// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.
Object.defineProperty(exports, "__esModule", { value: true });
exports.Ranker = void 0;
class Ranker {
    constructor(cli) {
        this.cli = cli;
    }
    CreateScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/CreateScoreboard", input);
    }
    UpdateScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/UpdateScoreboard", input);
    }
    RebuildScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/RebuildScoreboard", input);
    }
    DeleteScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/DeleteScoreboard", input);
    }
    LookupScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/LookupScoreboard", input);
    }
    DescribeScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/DescribeScoreboard", input);
    }
    ListScoreboards(input) {
        return this.cli.call("eolymp.ranker.Ranker/ListScoreboards", input);
    }
    ListScoreboardRows(input) {
        return this.cli.call("eolymp.ranker.Ranker/ListScoreboardRows", input);
    }
    AssignContest(input) {
        return this.cli.call("eolymp.ranker.Ranker/AssignContest", input);
    }
    UnassignContest(input) {
        return this.cli.call("eolymp.ranker.Ranker/UnassignContest", input);
    }
}
exports.Ranker = Ranker;
//# sourceMappingURL=ranker.js.map