"use strict";
// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.
Object.defineProperty(exports, "__esModule", { value: true });
exports.Ranker = void 0;
class Ranker {
    constructor(cli) {
        this.cli = cli;
    }
    CreateScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/CreateScoreboard", input);
    }
    UpdateScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/UpdateScoreboard", input);
    }
    RebuildScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/RebuildScoreboard", input);
    }
    DeleteScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/DeleteScoreboard", input);
    }
    LookupScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/LookupScoreboard", input);
    }
    DescribeScoreboard(input) {
        return this.cli.call("eolymp.ranker.Ranker/DescribeScoreboard", input);
    }
    ListScoreboards(input) {
        return this.cli.call("eolymp.ranker.Ranker/ListScoreboards", input);
    }
    DescribeScoreboardRow(input) {
        return this.cli.call("eolymp.ranker.Ranker/DescribeScoreboardRow", input);
    }
    ListScoreboardRows(input) {
        return this.cli.call("eolymp.ranker.Ranker/ListScoreboardRows", input);
    }
    AddScoreboardColumn(input) {
        return this.cli.call("eolymp.ranker.Ranker/AddScoreboardColumn", input);
    }
    DeleteScoreboardColumn(input) {
        return this.cli.call("eolymp.ranker.Ranker/DeleteScoreboardColumn", input);
    }
    DescribeScoreboardColumn(input) {
        return this.cli.call("eolymp.ranker.Ranker/DescribeScoreboardColumn", input);
    }
    ListScoreboardColumns(input) {
        return this.cli.call("eolymp.ranker.Ranker/ListScoreboardColumns", input);
    }
}
exports.Ranker = Ranker;
//# sourceMappingURL=ranker.js.map