// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { DeleteMessageInput, DeleteMessageOutput, DescribeMessageInput, DescribeMessageOutput, ListMessageChangesInput, ListMessageChangesOutput, ListMessagesInput, ListMessagesOutput, PostMessageInput, PostMessageOutput, UpdateMessageInput, UpdateMessageOutput, VoteMessageInput, VoteMessageOutput } from "./message_service"
import { DescribeSubscriptionInput, DescribeSubscriptionOutput, UpdateSubscriptionInput, UpdateSubscriptionOutput } from "./subscription_service"

interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class DiscussionService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }
}

