// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Subscription } from "./subscription"

export type Thread = {
  id?: string;
  url?: string;
  name?: string;
  vote?: number;
  voteCount?: number;
  replyCount?: number;
  subscription?: Subscription;
}

