// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Content } from "../ecm/content"

export type Newsletter = {
  id?: string;
  type?: string;
  createdAt?: string;
  scheduledAt?: string;
  name?: string;
  subject?: string;
  content?: Content;
  automatic?: boolean;
  locale?: string;
  locales?: string[];
  recipientsCount?: number;
  pendingCount?: number;
  sentCount?: number;
  errorCount?: number;
}

export type Newsletter_Extra = Record<string, unknown>;

export type Newsletter_Patch = {
  type?: string;
  name?: string;
  subject?: string;
  content?: Content;
  automatic?: boolean;
  scheduledAt?: string;
  unschedule?: boolean;
}

