// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { ExpressionID, ExpressionString } from "../wellknown/expression"
import { Template, Template_Patch } from "./template"

interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class TemplateService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  CreateTemplate(input: CreateTemplateInput, opts?: any): Promise<CreateTemplateOutput> {
    const path = "/email-templates";

    return this.cli.call("POST", this.url+path, input, opts);
  }

  UpdateTemplate(input: UpdateTemplateInput, opts?: any): Promise<UpdateTemplateOutput> {
    const path = "/email-templates/"+encodeURIComponent(input.templateId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.templateId);

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  DeleteTemplate(input: DeleteTemplateInput, opts?: any): Promise<DeleteTemplateOutput> {
    const path = "/email-templates/"+encodeURIComponent(input.templateId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.templateId);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  DescribeTemplate(input: DescribeTemplateInput, opts?: any): Promise<DescribeTemplateOutput> {
    const path = "/email-templates/"+encodeURIComponent(input.templateId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.templateId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListTemplates(input: ListTemplatesInput, opts?: any): Promise<ListTemplatesOutput> {
    const path = "/email-templates";

    return this.cli.call("GET", this.url+path, input, opts);
  }
}

export type CreateTemplateInput = {
  template?: Template;
}

export type CreateTemplateOutput = {
  templateId?: string;
}

export type UpdateTemplateInput = {
  templateId?: string;
  locale?: string;
  template?: Template_Patch;
}

export type UpdateTemplateOutput = Record<string, unknown>;

export type DeleteTemplateInput = {
  templateId?: string;
  locale?: string;
}

export type DeleteTemplateOutput = Record<string, unknown>;

export type DescribeTemplateInput = {
  templateId?: string;
  locale?: string;
  extra?: string[];
}

export type DescribeTemplateOutput = {
  template?: Template;
}

export type ListTemplatesInput = {
  offset?: number;
  size?: number;
  filters?: ListTemplatesInput_Filter;
  sort?: string;
  order?: string;
  locale?: string;
  extra?: string[];
}

export type ListTemplatesInput_Filter = {
  id?: ExpressionID[];
  key?: ExpressionString[];
}

export type ListTemplatesOutput = {
  total?: number;
  items?: Template[];
}

