// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Assignment = {
  status?: string;
  startAfter?: string;
  completeBefore?: string;
  startedAt?: string;
  completedAt?: string;
  duration?: number;
  progress?: number;
  grade?: number;
}

