// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Assignment = {
  id?: string;
  memberId?: string;
  groupId?: string;
  status?: string;
  startAfter?: string;
  completeBefore?: string;
  duration?: number;
  items?: Assignment_Item[];
  createdAt?: string;
  startedAt?: string;
  completedAt?: string;
}

export type Assignment_Item = {
  wildcard?: boolean;
  moduleId?: string;
  itemId?: string;
}

