// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { ModuleItem } from "./module_item"

export type AssignmentItemV2 = {
  item?: ModuleItem;
  progress?: number;
  grade?: number;
  excused?: boolean;
  gradedAt?: string;
}

