// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Content } from "../ecm/content"
import { Section } from "./entry_section"
import { Video } from "./entry_video"

export type Entry = {
  id?: string;
  title?: string;
  parentId?: string;
  depth?: number;
  durationEstimate?: number;
  section?: Section;
  document?: Content;
  video?: Video;
}

