// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Content } from "../ecm/content"

export type Module = {
  id?: string;
  url?: string;
  draft?: boolean;
  name?: string;
  imageUrl?: string;
  index?: number;
  description?: Content;
  assignment?: Module_Assignment;
}

export type Module_Assignment = {
  status?: string;
  progress?: number;
  grade?: number;
  dueTime?: string;
  startTime?: string;
  endTime?: string;
}

