// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Template } from "../atlas/code_template"
import { Question } from "../atlas/question"
import { Statement } from "../atlas/statement"
import { Test } from "../atlas/testing_test"
import { Runtime } from "../runtime/runtime"
import { CreateRunInput, CreateRunOutput, DescribeRunInput, DescribeRunOutput, WatchRunInput, WatchRunOutput } from "./run_service"
import { CreateSubmissionInput, CreateSubmissionOutput, DescribeSubmissionInput, DescribeSubmissionOutput, ListSubmissionsInput, ListSubmissionsOutput, WatchSubmissionInput, WatchSubmissionOutput } from "./submission_service"

interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
  stream<R, E>(verb: string, url: string, args: R, opts?: any): _Stream<E>;
}

interface _Stream<T> {
  on(event: "message", handler: (message: T) => void): this;
  on(event: "error", handler: (error: Error) => void): this;
  on(event: "eof", handler: () => void): this;
  close(): void;
  readonly closed: boolean;
}

export class ProblemService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  ListStatements(input: ListStatementsInput, opts?: any): Promise<ListStatementsOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/statements";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListQuestions(input: ListQuestionsInput, opts?: any): Promise<ListQuestionsOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/questions";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  LookupStatement(input: LookupStatementInput, opts?: any): Promise<LookupStatementOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/statements:lookup";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListExamples(input: ListExamplesInput, opts?: any): Promise<ListExamplesOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/examples";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  CreateSubmission(input: CreateSubmissionInput, opts?: any): Promise<CreateSubmissionOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/submissions";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  ListSubmissions(input: ListSubmissionsInput, opts?: any): Promise<ListSubmissionsOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/submissions";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DescribeSubmission(input: DescribeSubmissionInput, opts?: any): Promise<DescribeSubmissionOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/submissions/"+encodeURIComponent(input.submissionId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);
    delete(input.submissionId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  WatchSubmission(input: WatchSubmissionInput, opts?: any): _Stream<WatchSubmissionOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/submissions/"+encodeURIComponent(input.submissionId||'')+"/watch";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);
    delete(input.submissionId);

    return this.cli.stream("GET", this.url+path, input, opts);
  }

  LookupCodeTemplate(input: LookupCodeTemplateInput, opts?: any): Promise<LookupCodeTemplateOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/template";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  CreateRun(input: CreateRunInput, opts?: any): Promise<CreateRunOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/runs";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  DescribeRun(input: DescribeRunInput, opts?: any): Promise<DescribeRunOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/runs/"+encodeURIComponent(input.runId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);
    delete(input.runId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  WatchRun(input: WatchRunInput, opts?: any): _Stream<WatchRunOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/runs/"+encodeURIComponent(input.runId||'')+"/watch";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);
    delete(input.runId);

    return this.cli.stream("GET", this.url+path, input, opts);
  }

  ListRuntimes(input: ListRuntimesInput, opts?: any): Promise<ListRuntimesOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/materials/"+encodeURIComponent(input.materialId||'')+"/runtime";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.materialId);

    return this.cli.call("GET", this.url+path, input, opts);
  }
}

export type ListStatementsInput = {
  courseId?: string;
  materialId?: string;
}

export type ListStatementsOutput = {
  total?: number;
  items?: Statement[];
}

export type ListQuestionsInput = {
  courseId?: string;
  materialId?: string;
}

export type ListQuestionsOutput = {
  total?: number;
  items?: Question[];
}

export type LookupStatementInput = {
  courseId?: string;
  materialId?: string;
  locale?: string;
}

export type LookupStatementOutput = {
  statement?: Statement;
}

export type ListExamplesInput = {
  courseId?: string;
  materialId?: string;
}

export type ListExamplesOutput = {
  examples?: Test[];
}

export type LookupCodeTemplateInput = {
  courseId?: string;
  materialId?: string;
  runtime?: string;
}

export type LookupCodeTemplateOutput = {
  template?: Template;
}

export type ListRuntimesInput = {
  courseId?: string;
  materialId?: string;
}

export type ListRuntimesOutput = {
  total?: number;
  items?: Runtime[];
}

