// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Student = {
  id?: string;
  memberId?: string;
  displayName?: string;
  overallProgress?: number;
  overallGrade?: number;
  grades?: Student_Grade[];
  updatedAt?: string;
  gradedAt?: string;
}

export type Student_Grade = {
  entryId?: string;
  progress?: number;
  grade?: number;
}

