// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Submission, Submission_Output, Submission_Quiz } from "../atlas/submission"
import { ExpressionEnum, ExpressionFloat, ExpressionID, ExpressionTimestamp } from "../wellknown/expression"

interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
  stream<R, E>(verb: string, url: string, args: R, opts?: any): _Stream<E>;
}

interface _Stream<T> {
  on(event: "message", handler: (message: T) => void): this;
  on(event: "error", handler: (error: Error) => void): this;
  on(event: "eof", handler: () => void): this;
  close(): void;
  readonly closed: boolean;
}

export class SubmissionService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  CreateSubmission(input: CreateSubmissionInput, opts?: any): Promise<CreateSubmissionOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/submissions";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  ListSubmissions(input: ListSubmissionsInput, opts?: any): Promise<ListSubmissionsOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/submissions";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DescribeSubmission(input: DescribeSubmissionInput, opts?: any): Promise<DescribeSubmissionOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/submissions/"+encodeURIComponent(input.submissionId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.submissionId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  WatchSubmission(input: WatchSubmissionInput, opts?: any): _Stream<WatchSubmissionOutput> {
    const path = "/courses/"+encodeURIComponent(input.courseId||'')+"/submissions/"+encodeURIComponent(input.submissionId||'')+"/watch";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.courseId);
    delete(input.submissionId);

    return this.cli.stream("GET", this.url+path, input, opts);
  }
}

export type CreateSubmissionInput = {
  courseId?: string;
  materialId?: string;
  runtime?: string;
  source?: string;
  output?: Submission_Output;
  quiz?: Submission_Quiz;
}

export type CreateSubmissionOutput = {
  submissionId?: string;
}

export type ListSubmissionsInput = {
  courseId?: string;
  after?: string;
  size?: number;
  filters?: ListSubmissionsInput_Filter;
}

export type ListSubmissionsInput_Filter = {
  id?: ExpressionID[];
  memberId?: ExpressionID[];
  materialId?: ExpressionID[];
  submittedAt?: ExpressionTimestamp[];
  runtime?: ExpressionEnum[];
  status?: ExpressionEnum[];
  verdict?: ExpressionEnum[];
  score?: ExpressionFloat[];
  percentage?: ExpressionFloat[];
}

export type ListSubmissionsOutput = {
  total?: number;
  items?: Submission[];
  nextPageCursor?: string;
}

export type DescribeSubmissionInput = {
  courseId?: string;
  submissionId?: string;
}

export type DescribeSubmissionOutput = {
  submission?: Submission;
}

export type WatchSubmissionInput = {
  courseId?: string;
  submissionId?: string;
}

export type WatchSubmissionOutput = {
  submission?: Submission;
  event?: string;
}

