// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-eolymp for more details.


export type User = {
    id?: string;
    username?: string;
    name?: string;
    picture?: string;
    country?: string;
}

