// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type User = {
  id?: string;
  username?: string;
  email?: string;
  active?: boolean;
  rank?: number;
  rankTrend?: string;
  name?: string;
  picture?: string;
  company?: string;
  occupation?: string;
  country?: string;
  city?: string;
  emailStatus?: string;
  birthday?: string;
  registeredOn?: string;
  lastActivity?: string;
}

