// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Report } from "./report"
import { Status } from "./status"

export type StatusUpdatedEvent = {
  status?: Status;
}

export type JobReportedEvent = {
  report?: Report;
}

