// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-eolymp for more details.

import { Task } from "./task"

interface Client {
  call<R, E>(method: string, args: R): Promise<E>;
}

export class Executor {
  private readonly cli: Client;

  constructor(cli: Client) {
    this.cli = cli;
  }

  CreateTask(input: CreateTaskInput): Promise<CreateTaskOutput> {
    return this.cli.call("eolymp.executor.Executor/CreateTask", input);
  }
}

export type CreateTaskInput = {
  task?: Task;
}

export type CreateTaskOutput = Record<string, unknown>;

