// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Stats } from "./stats"

export type GenerationReport = {
  taskId?: string;
  reference?: string;
  origin?: string;
  agent?: string;
  error?: string;
  runs?: GenerationReport_Run[];
}

export type GenerationReport_Run = {
  reference?: string;
  status?: string;
  inputUrl?: string;
  answerUrl?: string;
  inputGeneratorStats?: Stats;
  answerGeneratorStats?: Stats;
}

