// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Interactor = {
  type?: string;
  lang?: string;
  source?: string;
  files?: Interactor_File[];
}

export type Interactor_File = {
  path?: string;
  sourceErn?: string;
}

