// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Script } from "./script"

export type StressTask = {
  taskId?: string;
  reference?: string;
  origin?: string;
  metadata?: Record<string, string>;
  wallTimeLimit?: number;
  cpuTimeLimit?: number;
  memoryLimit?: number;
  iterationCount?: number;
  runCount?: number;
  interactiveFollowup?: boolean;
  interactor?: Script;
  validator?: Script;
  generator?: Script;
  solution?: Script;
}

