// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Checker } from "./checker"
import { Interactor } from "./interactor"

export type Task = {
  reference?: string;
  origin?: string;
  priority?: number;
  runtime?: string;
  source?: string;
  sourceUrl?: string;
  headerUrl?: string;
  footerUrl?: string;
  redirectStderrToStdout?: boolean;
  runCount?: number;
  preconditions?: Task_Precondition[];
  constraints?: Task_Constraint[];
  checker?: Checker;
  interactor?: Interactor;
  runs?: Task_Run[];
  files?: Task_File[];
}

export type Task_File = {
  path?: string;
  sourceUrl?: string;
}

export type Task_Run = {
  reference?: string;
  index?: number;
  debug?: boolean;
  cost?: number;
  labels?: string[];
  inputObjectId?: string;
  inputContent?: string;
  inputUrl?: string;
  answerObjectId?: string;
  answerContent?: string;
  answerUrl?: string;
}

export type Task_Precondition = {
  selector?: string[];
  dependsOn?: string[];
  stopOnFailure?: boolean;
  maxExecutionTime?: number;
}

export type Task_Constraint = {
  selector?: string[];
  actor?: string;
  wallTimeLimit?: number;
  cpuTimeLimit?: number;
  memoryLimit?: number;
  fileSizeLimit?: number;
}

