// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { EvaluationTask } from "./evaluation_task"
import { GenerationTask } from "./generation_task"

interface Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class TaskService {
  private readonly cli: Client;
  private readonly url: string;

  constructor(cli: Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }
}

export type CreateTaskInput = {
  evaluation?: EvaluationTask;
  generation?: GenerationTask;
}

export type CreateTaskOutput = {
  taskId?: string;
}

