// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Verifier = {
  type?: string;
  lang?: string;
  source?: string;
  precision?: number;
  caseSensitive?: boolean;
  orderSensitive?: boolean;
  files?: Verifier_File[];
}

export type Verifier_File = {
  path?: string;
  sourceErn?: string;
}

