// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Warning = {
  source?: string;
  file?: string;
  line?: number;
  column?: number;
  message?: string;
  severity?: string;
}

