// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Value = {
  id?: string;
  name?: string;
  summary?: string;
  abbr?: string;
  image?: string;
  keywords?: string[];
}

export type Value_Translation = {
  locale?: string;
  name?: string;
  abbr?: string;
  summary?: string;
  keywords?: string[];
}

