// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Country = {
  id?: string;
  name?: string;
  localName?: string;
  flagUrl?: string;
}

