// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Log = {
  timestamp?: string;
  subject?: string;
  ipAddress?: string;
  userAgent?: string;
  method?: string;
  scope?: string;
  mutation?: boolean;
  operation?: string;
  payload?: string;
}

export type Log_Extra = Record<string, unknown>;

