// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Inline } from "./inline"

export type Container = {
  children?: Block[];
}

export type Block = {
  paragraph?: Block_Paragraph;
  layout?: Block_Layout;
  code?: Block_Code;
  math?: Block_Math;
  image?: Block_Image;
  heading?: Block_Heading;
  list?: Block_List;
  embed?: Block_Embed;
  table?: Block_Table;
  problemSection?: Block_ProblemSection;
  exampleList?: Block_ProblemExampleList;
  exampleInline?: Block_ProblemExampleInline;
  exampleFile?: Block_ProblemExampleFile;
}

export type Block_Paragraph = {
  children?: Inline[];
}

export type Block_Layout = {
  direction?: string;
  alignItems?: string;
  alignContent?: string;
  justifyItems?: string;
  justifyContent?: string;
  gap?: number;
  padding?: number[];
  children?: Container[];
}

export type Block_List = {
  style?: string;
  children?: Block_List_Item[];
}

export type Block_List_Item = {
  children?: Block[];
}

export type Block_Image = {
  src?: string;
  alt?: string;
  title?: string;
  width?: number;
  height?: number;
  zoomable?: boolean;
}

export type Block_Heading = {
  level?: number;
  children?: Inline[];
}

export type Block_Math = {
  content?: string;
}

export type Block_Code = {
  lang?: string;
  content?: string;
}

export type Block_Embed = {
  path?: string;
  values?: Block_Embed_Value[];
}

export type Block_Embed_Value = {
  name?: string;
  value?: string;
}

export type Block_Table = {
  header?: string;
  children?: Block_Table_Row[];
}

export type Block_Table_Row = {
  children?: Block_Table_Cell[];
}

export type Block_Table_Cell = {
  children?: Block[];
}

export type Block_ProblemSection = {
  type?: string;
  children?: Block[];
}

export type Block_ProblemExampleList = Record<string, unknown>;

export type Block_ProblemExampleFile = {
  number?: number;
}

export type Block_ProblemExampleInline = {
  number?: number;
  input?: string;
  answer?: string;
}

