// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Inline = {
  text?: Inline_Text;
  link?: Inline_Link;
  math?: Inline_Math;
  code?: Inline_Code;
  variable?: Inline_Variable;
}

export type Inline_Style = {
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  strikethrough?: boolean;
}

export type Inline_Text = {
  str?: string;
  style?: Inline_Style;
}

export type Inline_Link = {
  url?: string;
  children?: Inline[];
}

export type Inline_Math = {
  content?: string;
}

export type Inline_Code = {
  content?: string;
}

export type Inline_Variable = {
  name?: string;
  style?: Inline_Style;
}

