// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Credit = {
  id?: string;
  reference?: string;
  note?: string;
  amount?: number;
  grantedAt?: string;
  expiresAt?: string;
}

