// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Group = {
  id?: string;
  key?: string;
  name?: string;
  description?: string;
  index?: number;
  icon?: string;
  badge?: string;
  color?: string;
}

export type Group_Patch = Record<string, unknown>;

