// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Identity = {
  id?: string;
  issuer?: string;
  subject?: string;
  createdAt?: string;
  email?: string;
  emailVerified?: boolean;
  password?: string;
  passwordAge?: number;
  name?: string;
  nickname?: string;
  nicknameChangeTimeout?: number;
  picture?: string;
  locale?: string;
  timezone?: string;
  birthday?: string;
  country?: string;
  city?: string;
  company?: string;
  businessTitle?: string;
  preferredRuntime?: string;
}

