// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { User } from "./member_user"

export type Team = {
  staffed?: boolean;
  users?: User[];
}

