// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Attribute_Value } from "./attribute"
import { Member } from "./member"

interface Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class MembershipService {
  private readonly cli: Client;
  private readonly url: string;

  constructor(cli: Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  JoinSpace(input: JoinSpaceInput, opts?: any): Promise<JoinSpaceOutput> {
    const path = "/members/_self";

    return this.cli.call("POST", this.url+path, input, opts);
  }

  DescribeMembership(input: DescribeMembershipInput, opts?: any): Promise<DescribeMembershipOutput> {
    const path = "/members/_self";

    return this.cli.call("GET", this.url+path, input, opts);
  }

  UpdateMembership(input: UpdateMembershipInput, opts?: any): Promise<UpdateMembershipOutput> {
    const path = "/members/_self/attributes";

    return this.cli.call("POST", this.url+path, input, opts);
  }
}

export type JoinSpaceInput = {
  nickname?: string;
  attributes?: Attribute_Value[];
}

export type JoinSpaceOutput = Record<string, unknown>;

export type DescribeMembershipInput = Record<string, unknown>;

export type DescribeMembershipOutput = {
  member?: Member;
}

export type UpdateMembershipInput = {
  attributes?: Attribute_Value[];
}

export type UpdateMembershipOutput = Record<string, unknown>;

