// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { ExpressionEnum, ExpressionID } from "../wellknown/expression"
import { Notebook } from "./notebook"

interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class NotebookService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  UploadNotebook(input: UploadNotebookInput, opts?: any): Promise<UploadNotebookOutput> {
    const path = "/notebooks";

    return this.cli.call("POST", this.url+path, input, opts);
  }

  ReviewNotebook(input: ReviewNotebookInput, opts?: any): Promise<ReviewNotebookOutput> {
    const path = "/notebooks/"+encodeURIComponent(input.notebookId||'')+"/review";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.notebookId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  DeleteNotebook(input: DeleteNotebookInput, opts?: any): Promise<DeleteNotebookOutput> {
    const path = "/notebooks/"+encodeURIComponent(input.notebookId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.notebookId);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  DescribeNotebook(input: DescribeNotebookInput, opts?: any): Promise<DescribeNotebookOutput> {
    const path = "/notebooks/"+encodeURIComponent(input.notebookId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.notebookId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListNotebooks(input: ListNotebooksInput, opts?: any): Promise<ListNotebooksOutput> {
    const path = "/notebooks";

    return this.cli.call("GET", this.url+path, input, opts);
  }
}

export type UploadNotebookInput = {
  memberId?: string;
  name?: string;
  type?: string;
  contentUrl?: string;
}

export type UploadNotebookOutput = {
  notebookId?: string;
}

export type ReviewNotebookInput = {
  notebookId?: string;
  status?: string;
}

export type ReviewNotebookOutput = Record<string, unknown>;

export type DeleteNotebookInput = {
  notebookId?: string;
}

export type DeleteNotebookOutput = Record<string, unknown>;

export type DescribeNotebookInput = {
  notebookId?: string;
}

export type DescribeNotebookOutput = {
  notebook?: Notebook;
}

export type ListNotebooksInput = {
  offset?: number;
  size?: number;
  filters?: ListNotebooksInput_Filter;
}

export type ListNotebooksInput_Filter = {
  id?: ExpressionID[];
  memberId?: ExpressionID[];
  status?: ExpressionEnum[];
}

export type ListNotebooksOutput = {
  total?: number;
  items?: Notebook[];
}

