// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Penalty = {
  id?: string;
  summary?: string;
  scope?: string[];
  createdAt?: string;
  expiresAt?: string;
}

