// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type RankingEvent = {
  id?: string;
  name?: string;
  timestamp?: string;
  contestId?: string;
}

