// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type RatingPoint = {
  id?: string;
  ref?: string;
  timestamp?: string;
  value?: number;
  source?: RatingPoint_Source;
  targetLink?: string;
}

export type RatingPoint_Source = {
  id?: string;
  url?: string;
  name?: string;
  score?: number;
  penalty?: number;
  tieBreaker?: number;
  rank?: number;
  rankLower?: number;
  rankTotal?: number;
}

