// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type RatingPoint = {
  id?: string;
  timestamp?: string;
  value?: number;
  contestId?: string;
  ref?: string;
  targetLink?: string;
}

