// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Session = {
  id?: string;
  userAgent?: string;
  device?: string;
  location?: string;
  ipAddress?: string;
  firstSeenAt?: string;
  lastSeenAt?: string;
}

