// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { ExpressionEnum, ExpressionID } from "../wellknown/expression"
import { Achievement, Achievement_Translation } from "./achievement"

interface Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class AchievementService {
  private readonly cli: Client;
  private readonly url: string;

  constructor(cli: Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  CreateAchievement(input: CreateAchievementInput, opts?: any): Promise<CreateAchievementOutput> {
    const path = "/achievements";

    return this.cli.call("POST", this.url+path, input, opts);
  }

  UpdateAchievement(input: UpdateAchievementInput, opts?: any): Promise<UpdateAchievementOutput> {
    const path = "/achievements/"+encodeURIComponent(input.achievementId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.achievementId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  DeleteAchievement(input: DeleteAchievementInput, opts?: any): Promise<DeleteAchievementOutput> {
    const path = "/achievements/"+encodeURIComponent(input.achievementId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.achievementId);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  DescribeAchievement(input: DescribeAchievementInput, opts?: any): Promise<DescribeAchievementOutput> {
    const path = "/achievements/"+encodeURIComponent(input.achievementId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.achievementId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListAchievements(input: ListAchievementsInput, opts?: any): Promise<ListAchievementsOutput> {
    const path = "/achievements";

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DescribeAchievementTranslation(input: DescribeAchievementTranslationInput, opts?: any): Promise<DescribeAchievementTranslationOutput> {
    const path = "/achievements/"+encodeURIComponent(input.achievementId||'')+"/translations/"+encodeURIComponent(input.translationId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.achievementId);
    delete(input.translationId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListAchievementTranslations(input: ListAchievementTranslationsInput, opts?: any): Promise<ListAchievementTranslationsOutput> {
    const path = "/achievements/"+encodeURIComponent(input.achievementId||'')+"/translations";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.achievementId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  CreateAchievementTranslation(input: CreateAchievementTranslationInput, opts?: any): Promise<CreateAchievementTranslationOutput> {
    const path = "/achievements/"+encodeURIComponent(input.achievementId||'')+"/translations";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.achievementId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  UpdateAchievementTranslation(input: UpdateAchievementTranslationInput, opts?: any): Promise<UpdateAchievementTranslationOutput> {
    const path = "/achievements/"+encodeURIComponent(input.achievementId||'')+"/translations/"+encodeURIComponent(input.translationId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.achievementId);
    delete(input.translationId);

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  DeleteAchievementTranslation(input: DeleteAchievementTranslationInput, opts?: any): Promise<DeleteAchievementTranslationOutput> {
    const path = "/achievements/"+encodeURIComponent(input.achievementId||'')+"/translations/"+encodeURIComponent(input.translationId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.achievementId);
    delete(input.translationId);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }
}

export type CreateAchievementInput = {
  achievement?: Achievement;
}

export type CreateAchievementOutput = {
  achievementId?: string;
}

export type UpdateAchievementInput = {
  achievementId?: string;
  achievement?: Achievement;
}

export type UpdateAchievementOutput = Record<string, unknown>;

export type DeleteAchievementInput = {
  achievementId?: string;
}

export type DeleteAchievementOutput = Record<string, unknown>;

export type DescribeAchievementInput = {
  achievementId?: string;
  extra?: string[];
}

export type DescribeAchievementOutput = {
  achievement?: Achievement;
}

export type ListAchievementsInput = {
  after?: string;
  size?: number;
  offset?: number;
  filters?: ListAchievementsInput_Filter;
  extra?: string[];
}

export type ListAchievementsInput_Filter = {
  query?: string;
  id?: ExpressionID[];
}

export type ListAchievementsOutput = {
  total?: number;
  items?: Achievement[];
}

export type DescribeAchievementTranslationInput = {
  achievementId?: string;
  translationId?: string;
  extra?: string[];
}

export type DescribeAchievementTranslationOutput = {
  translation?: Achievement_Translation;
}

export type ListAchievementTranslationsInput = {
  achievementId?: string;
  offset?: number;
  size?: number;
  filters?: ListAchievementTranslationsInput_Filter;
  extra?: string[];
}

export type ListAchievementTranslationsInput_Filter = {
  query?: string;
  id?: ExpressionID[];
  locale?: ExpressionEnum[];
}

export type ListAchievementTranslationsOutput = {
  total?: number;
  items?: Achievement_Translation[];
}

export type CreateAchievementTranslationInput = {
  achievementId?: string;
  translation?: Achievement_Translation;
}

export type CreateAchievementTranslationOutput = {
  translationId?: string;
}

export type UpdateAchievementTranslationInput = {
  patch?: string[];
  achievementId?: string;
  translationId?: string;
  translation?: Achievement_Translation;
}

export type UpdateAchievementTranslationOutput = Record<string, unknown>;

export type DeleteAchievementTranslationInput = {
  achievementId?: string;
  translationId?: string;
}

export type DeleteAchievementTranslationOutput = Record<string, unknown>;

