// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { ExpressionBool, ExpressionID } from "../wellknown/expression"
import { Chat, Message } from "./chat"

interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
  stream<R, E>(verb: string, url: string, args: R, opts?: any): _Stream<E>;
}

interface _Stream<T> {
  on(event: "message", handler: (message: T) => void): this;
  on(event: "error", handler: (error: Error) => void): this;
  on(event: "eof", handler: () => void): this;
  close(): void;
  readonly closed: boolean;
}

export class ChatService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  StartChat(input: StartChatInput, opts?: any): Promise<StartChatOutput> {
    const path = "/copilot/chats";

    return this.cli.call("POST", this.url+path, input, opts);
  }

  DescribeChat(input: DescribeChatInput, opts?: any): Promise<DescribeChatOutput> {
    const path = "/copilot/chats/"+encodeURIComponent(input.chatId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.chatId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListChats(input: ListChatsInput, opts?: any): Promise<ListChatsOutput> {
    const path = "/copilot/chats";

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ArchiveChat(input: ArchiveChatInput, opts?: any): Promise<ArchiveChatOutput> {
    const path = "/copilot/chats/"+encodeURIComponent(input.chatId||'')+"/archive";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.chatId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  DeleteChat(input: DeleteChatInput, opts?: any): Promise<DeleteChatOutput> {
    const path = "/copilot/chats/"+encodeURIComponent(input.chatId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.chatId);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  SendMessage(input: SendMessageInput, opts?: any): _Stream<SendMessageOutput> {
    const path = "/copilot/chats/"+encodeURIComponent(input.chatId||'')+"/messages";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.chatId);

    return this.cli.stream("POST", this.url+path, input, opts);
  }

  ListMessages(input: ListMessagesInput, opts?: any): Promise<ListMessagesOutput> {
    const path = "/copilot/chats/"+encodeURIComponent(input.chatId||'')+"/messages";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.chatId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DescribeChatOptions(input: DescribeChatOptionsInput, opts?: any): Promise<DescribeChatOptionsOutput> {
    const path = "/copilot/options";

    return this.cli.call("GET", this.url+path, input, opts);
  }
}

export type StartChatInput = Record<string, unknown>;

export type StartChatOutput = {
  chatId?: string;
}

export type DescribeChatInput = {
  chatId?: string;
}

export type DescribeChatOutput = {
  chat?: Chat;
}

export type ListChatsInput = {
  offset?: number;
  size?: number;
  query?: string;
  filters?: ListChatsInput_Filter;
  sort?: string;
  order?: string;
}

export type ListChatsInput_Filter = {
  id?: ExpressionID[];
  archived?: ExpressionBool[];
}

export type ListChatsOutput = {
  total?: number;
  items?: Chat[];
}

export type ArchiveChatInput = {
  chatId?: string;
  unarchive?: boolean;
}

export type ArchiveChatOutput = Record<string, unknown>;

export type DeleteChatInput = {
  chatId?: string;
}

export type DeleteChatOutput = Record<string, unknown>;

export type SendMessageInput = {
  chatId?: string;
  model?: string;
  message?: SendMessageInput_Message;
  approval?: SendMessageInput_Approval;
}

export type SendMessageInput_Message = {
  text?: string;
}

export type SendMessageInput_Approval = {
  allow?: string[];
  reject?: string[];
}

export type SendMessageOutput = {
  chat?: Chat;
  message?: Message;
  status?: string;
}

export type ListMessagesInput = {
  chatId?: string;
  offset?: number;
  size?: number;
  filters?: ListMessagesInput_Filter;
  sort?: string;
  order?: string;
}

export type ListMessagesInput_Filter = {
  id?: ExpressionID[];
}

export type ListMessagesOutput = {
  total?: number;
  items?: Message[];
}

export type DescribeChatOptionsInput = Record<string, unknown>;

export type DescribeChatOptionsOutput = {
  models?: DescribeChatOptionsOutput_Model[];
}

export type DescribeChatOptionsOutput_Model = {
  id?: string;
  name?: string;
}

