// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


interface Client {
  call<R, E, O>(method: string, args: R, opts: O): Promise<E>;
}

export class Keeper {
  private readonly cli: Client;

  constructor(cli: Client) {
    this.cli = cli;
  }

  CreateObject<O>(input: CreateObjectInput, opts: O): Promise<CreateObjectOutput> {
    return this.cli.call("eolymp.keeper.Keeper/CreateObject", input, opts);
  }

  DescribeObject<O>(input: DescribeObjectInput, opts: O): Promise<DescribeObjectOutput> {
    return this.cli.call("eolymp.keeper.Keeper/DescribeObject", input, opts);
  }

  DownloadObject<O>(input: DownloadObjectInput, opts: O): Promise<DownloadObjectOutput> {
    return this.cli.call("eolymp.keeper.Keeper/DownloadObject", input, opts);
  }
}

export type CreateObjectInput = {
  data?: string;
}

export type CreateObjectOutput = {
  key?: string;
}

export type DescribeObjectInput = {
  key?: string;
}

export type DescribeObjectOutput = {
  size?: number;
}

export type DownloadObjectInput = {
  key?: string;
  offset?: number;
  size?: number;
}

export type DownloadObjectOutput = {
  data?: string;
  size?: number;
}

