// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Content } from "../ecm/content"

export type Fragment = {
  id?: string;
  resourceLink?: string;
  spaceLink?: string;
  consoleLink?: string;
  path?: string;
  parentId?: string;
  slug?: string;
  position?: number;
  locale?: string;
  locales?: string[];
  draft?: boolean;
  automatic?: boolean;
  visibility?: string;
  title?: string;
  content?: Content;
  createdAt?: string;
  updatedAt?: string;
  labels?: string[];
}

export type Fragment_Extra = Record<string, unknown>;

export type Fragment_Patch = {
  path?: string;
  parentId?: string;
  slug?: string;
  position?: number;
  draft?: boolean;
  automatic?: boolean;
  title?: string;
  visibility?: string;
  content?: Content;
  labels?: string[];
  unsetLabels?: boolean;
}

