// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-eolymp for more details.


export type Run = {
  id?: string;
  lang?: string;
  source?: string;
  input?: string;
  status?: string;
  error?: string;
  exitCode?: number;
  signal?: number;
  timeUsage?: number;
  memoryUsage?: number;
  output?: string;
}

