// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-eolymp for more details.

import {Submission} from "./submission"
import {Score} from "./score"

export type SubmissionCompletedEvent = {
    submission?: Submission;
    update?: boolean;
}

export type ScoreUpdatedEvent = {
    score?: Score;
}

export type StarAddedEvent = {
    problemId?: string;
    userId?: string;
}

export type StarRemovedEvent = {
    problemId?: string;
    userId?: string;
}

