// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Category = {
  id?: string;
  visible?: boolean;
  index?: number;
  parentId?: string;
  image?: string;
  descriptions?: Category_Description[];
}

export type Category_Description = {
  locale?: string;
  title?: string;
  summary?: string;
}

