// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { File } from "../executor/file"

export type Checker = {
  type?: string;
  runtime?: string;
  source?: string;
  precision?: number;
  caseSensitive?: boolean;
  orderSensitive?: boolean;
  secret?: boolean;
  files?: File[];
}

