// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Content } from "../ecm/content"

export type Issue = {
  id?: string;
  problemId?: string;
  number?: string;
  status?: string;
  title?: string;
  description?: Content;
  assignee?: string;
  reporterId?: string;
  testerId?: string;
  tags?: string[];
  createdAt?: string;
  updatedAt?: string;
}

export type Issue_Extra = Record<string, unknown>;

export type Issue_Patch = Record<string, unknown>;

