// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { ExpressionEnum, ExpressionID, ExpressionInt } from "../wellknown/expression"
import { Issue } from "./issue"
import { IssueActivity, IssueActivity_Comment } from "./issue_activity"

interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class IssueService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  ListIssues(input: ListIssuesInput, opts?: any): Promise<ListIssuesOutput> {
    const path = "/issues";

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DescribeIssue(input: DescribeIssueInput, opts?: any): Promise<DescribeIssueOutput> {
    const path = "/issues/"+encodeURIComponent(input.issueId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.issueId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  CreateIssue(input: CreateIssueInput, opts?: any): Promise<CreateIssueOutput> {
    const path = "/issues";

    return this.cli.call("POST", this.url+path, input, opts);
  }

  UpdateIssue(input: UpdateIssueInput, opts?: any): Promise<UpdateIssueOutput> {
    const path = "/issues/"+encodeURIComponent(input.issueId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.issueId);

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  DeleteIssue(input: DeleteIssueInput, opts?: any): Promise<DeleteIssueOutput> {
    const path = "/issues/"+encodeURIComponent(input.issueId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.issueId);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  ListIssueActivities(input: ListIssueActivitiesInput, opts?: any): Promise<ListIssueActivitiesOutput> {
    const path = "/issues/"+encodeURIComponent(input.issueId||'')+"/activities";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.issueId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  CreateIssueComment(input: CreateIssueCommentInput, opts?: any): Promise<CreateIssueCommentOutput> {
    const path = "/issues/"+encodeURIComponent(input.issueId||'')+"/comments";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.issueId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  UpdateIssueComment(input: UpdateIssueCommentInput, opts?: any): Promise<UpdateIssueCommentOutput> {
    const path = "/issues/"+encodeURIComponent(input.issueId||'')+"/comments/"+encodeURIComponent(input.commentId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.issueId);
    delete(input.commentId);

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  DeleteIssueComment(input: DeleteIssueCommentInput, opts?: any): Promise<DeleteIssueCommentOutput> {
    const path = "/issues/"+encodeURIComponent(input.issueId||'')+"/comments/"+encodeURIComponent(input.commentId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.issueId);
    delete(input.commentId);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }
}

export type IssueChangedEvent = {
  problemId?: string;
  before?: Issue;
  after?: Issue;
  actorId?: string;
}

export type ListIssuesInput = {
  offset?: number;
  size?: number;
  filters?: ListIssuesInput_Filter;
  sort?: string;
  order?: string;
  extra?: string[];
}

export type ListIssuesInput_Filter = {
  id?: ExpressionID[];
  problemId?: ExpressionID[];
  status?: ExpressionEnum[];
  number?: ExpressionInt[];
  assigneeId?: ExpressionID[];
  reporterId?: ExpressionID[];
  testerId?: ExpressionID[];
  tags?: ExpressionEnum[];
}

export type ListIssuesOutput = {
  total?: number;
  items?: Issue[];
}

export type DescribeIssueInput = {
  issueId?: string;
  extra?: string[];
}

export type DescribeIssueOutput = {
  issue?: Issue;
}

export type CreateIssueInput = {
  issue?: Issue;
}

export type CreateIssueOutput = {
  issueId?: string;
}

export type UpdateIssueInput = {
  patch?: string[];
  issueId?: string;
  issue?: Issue;
}

export type UpdateIssueOutput = Record<string, unknown>;

export type DeleteIssueInput = {
  issueId?: string;
}

export type DeleteIssueOutput = Record<string, unknown>;

export type ListIssueActivitiesInput = {
  issueId?: string;
  offset?: number;
  size?: number;
  sort?: string;
  order?: string;
  extra?: string[];
}

export type ListIssueActivitiesOutput = {
  total?: number;
  items?: IssueActivity[];
}

export type CreateIssueCommentInput = {
  issueId?: string;
  comment?: IssueActivity_Comment;
}

export type CreateIssueCommentOutput = {
  commentId?: string;
}

export type UpdateIssueCommentInput = {
  patch?: string[];
  issueId?: string;
  commentId?: string;
  comment?: IssueActivity_Comment;
}

export type UpdateIssueCommentOutput = Record<string, unknown>;

export type DeleteIssueCommentInput = {
  issueId?: string;
  commentId?: string;
}

export type DeleteIssueCommentOutput = Record<string, unknown>;

