// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


interface Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class PolygonService {
  private readonly cli: Client;
  private readonly url: string;

  constructor(cli: Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  ImportPolygonProblem(input: ImportPolygonProblemInput, opts?: any): Promise<ImportPolygonProblemOutput> {
    const path = "/polygon/import";

    return this.cli.call("POST", this.url+path, input, opts);
  }
}

export type ImportPolygonProblemInput = {
  url?: string;
  username?: string;
  password?: string;
}

export type ImportPolygonProblemOutput = {
  problemId?: string;
  jobId?: string;
}

