// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Problem = {
  id?: string;
  url?: string;
  links?: Record<string, string>;
  number?: number;
  visible?: boolean;
  private?: boolean;
  origin?: string;
  topics?: string[];
  minTimeLimit?: number;
  maxTimeLimit?: number;
  minCpuLimit?: number;
  maxCpuLimit?: number;
  minMemoryLimit?: number;
  maxMemoryLimit?: number;
  acceptanceRate?: number;
  submissionsCount?: number;
  submissionsAccepted?: number;
  vote?: number;
  voteCount?: number;
  difficulty?: number;
}

