// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Problem = {
  id?: string;
  url?: string;
  number?: number;
  visible?: boolean;
  private?: boolean;
  topics?: string[];
  difficulty?: number;
}

