// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Interactor } from "../executor/interactor"
import { Verifier } from "../executor/verifier"
import { Attachment } from "./attachment"
import { Template } from "./code_template"
import { Problem } from "./problem"
import { Statement } from "./statement"
import { Test } from "./testing_test"
import { Testset } from "./testing_testset"

export type Snapshot = {
  problem?: Problem[];
  checker?: Verifier;
  interactor?: Interactor;
  statements?: Statement[];
  templates?: Template[];
  attachments?: Attachment[];
  testsets?: Testset[];
  tests?: Test[];
}

