// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Statement = {
  id?: string;
  problemId?: string;
  locale?: string;
  title?: string;
  content?: string;
  downloadLink?: string;
  format?: string;
  author?: string;
  source?: string;
}

