// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


interface Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class SubmissionGraphService {
  private readonly cli: Client;
  private readonly url: string;

  constructor(cli: Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  ListSubmissionValues(input: ListSubmissionValuesInput, opts?: any): Promise<ListSubmissionValuesOutput> {
    const path = "/submissions-graph";

    return this.cli.call("GET", this.url+path, input, opts);
  }
}

export type ListSubmissionValuesInput = {
  after?: string;
  before?: string;
}

export type ListSubmissionValuesOutput = {
  values?: number[];
  maxValue?: number;
}

