// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Stats } from "../executor/stats"

export type Submission = {
  id?: string;
  problemId?: string;
  version?: number;
  userId?: string;
  memberId?: string;
  submittedAt?: string;
  judgedAt?: string;
  lang?: string;
  source?: string;
  sourceUrl?: string;
  quiz?: Submission_Quiz;
  output?: Submission_Output;
  signature?: string;
  status?: string;
  verdict?: string;
  error?: string;
  errorUrl?: string;
  cost?: number;
  score?: number;
  percentage?: number;
  timeUsage?: number;
  cpuUsage?: number;
  memoryUsage?: string;
  resourceUsage?: number;
  groups?: Submission_Group[];
  fingerprint?: Submission_Fingerprint;
  assistantAvailable?: boolean;
  cursor?: string;
}

export type Submission_Extra = Record<string, unknown>;

export type Submission_Run = {
  id?: string;
  index?: number;
  timeUsage?: number;
  cpuUsage?: number;
  memoryUsage?: string;
  resourceUsage?: number;
  inputUrl?: string;
  outputUrl?: string;
  answerUrl?: string;
  interactionUrl?: string;
  cost?: number;
  score?: number;
  status?: string;
  verdict?: string;
  debugStats?: Stats;
  checkerStats?: Stats;
  interactorStats?: Stats;
}

export type Submission_Group = {
  index?: number;
  status?: string;
  verdict?: string;
  dependencies?: number[];
  cost?: number;
  score?: number;
  scoringMode?: string;
  feedbackPolicy?: string;
  timeUsage?: number;
  cpuUsage?: number;
  memoryUsage?: string;
  resourceUsage?: number;
  runs?: Submission_Run[];
}

export type Submission_Quiz = {
  answers?: Submission_Quiz_Answer[];
}

export type Submission_Quiz_Choice = {
  id?: string;
  index?: number;
}

export type Submission_Quiz_Answer = {
  questionId?: string;
  questionIndex?: number;
  choices?: Submission_Quiz_Choice[];
  text?: string;
}

export type Submission_Output = {
  answers?: Submission_Output_Answer[];
}

export type Submission_Output_Answer = {
  testId?: string;
  index?: number;
  filename?: string;
  outputUrl?: string;
}

export type Submission_Fingerprint = {
  family?: string;
  tokens?: number;
  hashes?: string[];
}

