// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { File } from "../executor/file"

export type Checker = {
  versionId?: string;
  secret?: boolean;
  type?: string;
  runtime?: string;
  source?: string;
  files?: File[];
  precision?: number;
  caseSensitive?: boolean;
  orderSensitive?: boolean;
  tokens?: Checker_Tokens;
  lines?: Checker_Lines;
  program?: Checker_Program;
  queryResults?: Checker_QueryResults;
}

export type Checker_Tokens = {
  precision?: number;
  caseSensitive?: boolean;
}

export type Checker_Lines = Record<string, unknown>;

export type Checker_Program = {
  mode?: string;
  runtime?: string;
  source?: string;
  files?: File[];
}

export type Checker_QueryResults = {
  orderSensitive?: boolean;
}

