// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Topic = {
  id?: string;
  name?: string;
  summary?: string;
  keywords?: string[];
  variants?: Topic_Variant[];
}

export type Topic_Variant = {
  locale?: string;
  name?: string;
  summary?: string;
  keywords?: string[];
}

