// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Version = {
  id?: string;
  number?: number;
  createdAt?: string;
  createdBy?: string;
  changeOp?: string;
  changePath?: string;
  cursor?: string;
}

