// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-eolymp for more details.


export type Http = {
    rules?: HttpRule[];
    fullyDecodeReservedExpansion?: boolean;
}

export type HttpRule = {
    selector?: string;
    get?: string;
    put?: string;
    post?: string;
    delete?: string;
    patch?: string;
    custom?: CustomHttpPattern;
    body?: string;
    responseBody?: string;
    additionalBindings?: HttpRule[];
}

export type CustomHttpPattern = {
    kind?: string;
    path?: string;
}

