// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type MCP = Record<string, unknown>;

export type MCP_Tool = {
  name?: string;
  description?: string;
  requireConfirmation?: boolean;
}

