// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Content } from "../ecm/content"
import { Channel, Connection, Connection_Patch } from "./connection"

interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class ConnectionService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  DescribeConnection(input: DescribeConnectionInput, opts?: any): Promise<DescribeConnectionOutput> {
    const path = "/discord/connection";

    return this.cli.call("GET", this.url+path, input, opts);
  }

  UpdateConnection(input: UpdateConnectionInput, opts?: any): Promise<UpdateConnectionOutput> {
    const path = "/discord/connection";

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  DeleteConnection(input: DeleteConnectionInput, opts?: any): Promise<DeleteConnectionOutput> {
    const path = "/discord/connection";

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  ListChannels(input: ListChannelsInput, opts?: any): Promise<ListChannelsOutput> {
    const path = "/discord/channels";

    return this.cli.call("GET", this.url+path, input, opts);
  }
}

export type DescribeConnectionInput = Record<string, unknown>;

export type DescribeConnectionOutput = {
  connection?: Connection;
}

export type UpdateConnectionInput = {
  connection?: Connection_Patch;
}

export type UpdateConnectionOutput = Record<string, unknown>;

export type DeleteConnectionInput = Record<string, unknown>;

export type DeleteConnectionOutput = Record<string, unknown>;

export type ListChannelsInput = Record<string, unknown>;

export type ListChannelsOutput = {
  total?: number;
  items?: Channel[];
}

export type PostMessageInput = {
  channelId?: string;
  title?: string;
  content?: Content;
  validateOnly?: boolean;
}

export type PostMessageOutput = {
  messageId?: string;
  url?: string;
}

