// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Connection = {
  tokenSet?: boolean;
  guildId?: string;
  guildName?: string;
  botUsername?: string;
  connectedAt?: string;
}

export type Connection_Patch = {
  botToken?: string;
  guildId?: string;
}

export type Channel = {
  id?: string;
  name?: string;
  writable?: boolean;
}

