// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Quota } from "./quota"
import { Space } from "./space"

export type SpaceChangedEvent = {
  before?: Space;
  after?: Space;
}

export type QuotaChangedEvent = {
  spaceId?: string;
  before?: Quota;
  after?: Quota;
}

