// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Quota = {
  permissionsPerSpace?: number;
  singleSingOn?: boolean;
  dedicatedUserDatabase?: boolean;
  attributesPerSpace?: number;
  customerSupportReplyTime?: number;
  allowDiscussions?: boolean;
  achievementsPerSpace?: number;
  printersPerSpace?: number;
  evaluationsBySeatPerMonth?: number;
  priorityEvaluationQueue?: boolean;
  plagiarismAnalysis?: boolean;
  submissionEvaluationLimit?: number;
  membersPerSpace?: number;
  memberCredits?: boolean;
  campaignsPerSpace?: number;
  emailsPerDay?: number;
  emailsPerMonth?: number;
  scoreboardsPerSpace?: number;
  coursesPerSpace?: number;
  problemsPerSpace?: number;
  testsPerProblem?: number;
  testsetPerProblem?: number;
  statementPerProblem?: number;
  editorialPerProblem?: number;
  solutionsPerProblem?: number;
  codeTemplatesPerProblem?: number;
  debugAssistant?: boolean;
  debugHintsDailyPerAdmin?: number;
  debugHintsDailyPerMember?: number;
  contestsPerSpace?: number;
  activeContestsPerSpace?: number;
  contestsPerMonth?: number;
  problemsPerContest?: number;
  participantsPerContest?: number;
  contestUpsolveMode?: boolean;
  maxContestDuration?: number;
  teamContests?: boolean;
  ghostParticipants?: boolean;
  unofficialParticipants?: boolean;
}

