// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Quota } from "./quota"

export type Space = {
  id?: string;
  key?: string;
  url?: string;
  name?: string;
  image?: string;
  type?: string;
  visibility?: string;
  quota?: Quota;
  plan?: string;
  seats?: number;
  homeUrl?: string;
  issuerUrl?: string;
  graphqlUrl?: string;
}

