// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Space = {
  id?: string;
  key?: string;
  url?: string;
  name?: string;
  image?: string;
  type?: string;
  plan?: string;
  visibility?: string;
  membership?: string;
  minTeamSize?: number;
  maxTeamSize?: number;
}

export type Space_Quota = {
  problemsPerSpace?: number;
  membersPerSpace?: number;
  contestsPerSpace?: number;
  activeContestsPerSpace?: number;
  scoreboardsPerSpace?: number;
  permissionsPerSpace?: number;
  attributesPerSpace?: number;
  problemsPerContest?: number;
  participantsPerContest?: number;
}

export type Space_AuthenticationOAuth2 = {
  authorizeUrl?: string;
  tokenUrl?: string;
  introspectUrl?: string;
  signoutUrl?: string;
}

