// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type UserConfig = {
  basecamp?: UserConfig_BasecampProvider;
  local?: UserConfig_LocalProvider;
  oidc?: UserConfig_OIDCProvider;
  displayName?: string;
  displayNameAttribute?: string;
}

export type UserConfig_BasecampProvider = Record<string, unknown>;

export type UserConfig_LocalProvider = {
  allowModifyPassword?: boolean;
  allowModifyBasics?: boolean;
  allowModifyEmail?: boolean;
  allowModifyNickname?: boolean;
}

export type UserConfig_OIDCProvider = {
  clientId?: string;
  clientSecret?: string;
  issuer?: string;
  authorizeEndpoint?: string;
  tokenEndpoint?: string;
  keysEndpoint?: string;
  userinfoEndpoint?: string;
  redirectUri?: string;
}

