// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class ExecutionService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }
}

export type ExecuteTaskInput = {
  taskId?: string;
  task?: any;
  checkpoint?: any;
  attempt?: number;
}

export type ExecuteTaskOutput = {
  progress?: ExecuteTaskOutput_Progress;
  checkpoint?: ExecuteTaskOutput_Checkpoint;
  record?: ExecuteTaskOutput_Record;
}

export type ExecuteTaskOutput_Progress = {
  progress?: number;
  total?: number;
  statusMessage?: string;
}

export type ExecuteTaskOutput_Checkpoint = {
  checkpoint?: any;
}

export type ExecuteTaskOutput_Record = {
  line?: string;
}

