// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


interface Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class ConfigurationService {
  private readonly cli: Client;
  private readonly url: string;

  constructor(cli: Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  DescribeRuntimeConfig(input: DescribeRuntimeConfigInput, opts?: any): Promise<DescribeRuntimeConfigOutput> {
    const path = "/configs/runtime";

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ConfigureRuntimeConfig(input: ConfigureRuntimeConfigInput, opts?: any): Promise<ConfigureRuntimeConfigOutput> {
    const path = "/configs/runtime";

    return this.cli.call("PUT", this.url+path, input, opts);
  }
}

export type DescribeRuntimeConfigInput = Record<string, unknown>;

export type DescribeRuntimeConfigOutput = {
  allowedRuntime?: string[];
}

export type ConfigureRuntimeConfigInput = {
  allowedRuntime?: string[];
}

export type ConfigureRuntimeConfigOutput = Record<string, unknown>;

