// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Policy } from "./policy"

interface Client {
  call<R, E, O>(verb: string, url: string, args: R, opts: O): Promise<E>;
}

export class Guardian {
  private readonly cli: Client;
  private readonly url: string;

  constructor(cli: Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  ListPolicies<O>(input: ListPoliciesInput, opts?: O): Promise<ListPoliciesOutput> {
    const path = "/policies";

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DescribePolicy<O>(input: DescribePolicyInput, opts?: O): Promise<DescribePolicyOutput> {
    const path = "/policies/"+encodeURIComponent(input.id||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.id);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DefinePolicy<O>(input: DefinePolicyInput, opts?: O): Promise<DefinePolicyOutput> {
    const path = "/policies/"+encodeURIComponent(input.id||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.id);

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  RemovePolicy<O>(input: RemovePolicyInput, opts?: O): Promise<RemovePolicyOutput> {
    const path = "/policies/"+encodeURIComponent(input.id||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.id);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }
}

export type ListPoliciesInput = Record<string, unknown>;

export type ListPoliciesOutput = {
  total?: number;
  items?: Policy[];
}

export type DescribePolicyInput = {
  id?: string;
}

export type DescribePolicyOutput = {
  policy?: Policy;
}

export type DefinePolicyInput = {
  id?: string;
  policy?: Policy;
}

export type DefinePolicyOutput = Record<string, unknown>;

export type RemovePolicyInput = {
  id?: string;
}

export type RemovePolicyOutput = Record<string, unknown>;

