// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Policy = {
  id?: string;
  name?: string;
  principal?: string;
  statements?: Statement[];
}

export type Statement = {
  id?: string;
  effect?: string;
  resource?: string;
  actions?: string[];
}

