// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Country } from "./country"
import { Region } from "./region"

interface Client {
  call<R, E, O>(verb: string, url: string, args: R, opts: O): Promise<E>;
}

export class Geography {
  private readonly cli: Client;
  private readonly url: string;

  constructor(cli: Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  DescribeCountry<O>(input: DescribeCountryInput, opts?: O): Promise<DescribeCountryOutput> {
    const path = "/geography/countries/"+encodeURIComponent(input.countryId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.countryId);

    return this.cli.call("GET", this.url + path, input, opts);
  }

  ListCountries<O>(input: ListCountriesInput, opts?: O): Promise<ListCountriesOutput> {
    const path = "/geography/countries";

    return this.cli.call("GET", this.url + path, input, opts);
  }

  DescribeRegion<O>(input: DescribeRegionInput, opts?: O): Promise<DescribeRegionOutput> {
    const path = "/geography/regions/"+encodeURIComponent(input.regionId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.regionId);

    return this.cli.call("GET", this.url + path, input, opts);
  }

  ListRegions<O>(input: ListRegionsInput, opts?: O): Promise<ListRegionsOutput> {
    const path = "/geography/countries/"+encodeURIComponent(input.countryId||'')+"/regions";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.countryId);

    return this.cli.call("GET", this.url + path, input, opts);
  }
}

export type DescribeCountryInput = {
  countryId?: string;
}

export type DescribeCountryOutput = {
  country?: Country;
}

export type ListCountriesInput = Record<string, unknown>;

export type ListCountriesOutput = {
  items?: Country[];
  total?: number;
}

export type DescribeRegionInput = {
  regionId?: string;
}

export type DescribeRegionOutput = {
  region?: Region;
}

export type ListRegionsInput = {
  countryId?: string;
}

export type ListRegionsOutput = {
  items?: Region[];
  total?: number;
}

