// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { ExpressionID, ExpressionString } from "../wellknown/expression"
import { Country } from "./country"
import { Region } from "./region"

interface Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class Geography {
  private readonly cli: Client;
  private readonly url: string;

  constructor(cli: Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  DescribeCountry(input: DescribeCountryInput, opts?: any): Promise<DescribeCountryOutput> {
    const path = "/geography/countries/"+encodeURIComponent(input.countryId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.countryId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListCountries(input: ListCountriesInput, opts?: any): Promise<ListCountriesOutput> {
    const path = "/geography/countries";

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DescribeRegion(input: DescribeRegionInput, opts?: any): Promise<DescribeRegionOutput> {
    const path = "/geography/regions/"+encodeURIComponent(input.regionId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.regionId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListRegions(input: ListRegionsInput, opts?: any): Promise<ListRegionsOutput> {
    const path = "/geography/regions";

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DeprecatedListRegions(input: ListRegionsInput, opts?: any): Promise<ListRegionsOutput> {
    const path = "/geography/countries/"+encodeURIComponent(input.countryId||'')+"/regions";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.countryId);

    return this.cli.call("GET", this.url+path, input, opts);
  }
}

export type DescribeCountryInput = {
  countryId?: string;
}

export type DescribeCountryOutput = {
  country?: Country;
}

export type ListCountriesInput = {
  offset?: number;
  size?: number;
}

export type ListCountriesInput_Filter = {
  query?: string;
  id?: ExpressionID[];
  name?: ExpressionString[];
}

export type ListCountriesOutput = {
  items?: Country[];
  total?: number;
}

export type DescribeRegionInput = {
  regionId?: string;
}

export type DescribeRegionOutput = {
  region?: Region;
}

export type ListRegionsInput = {
  offset?: number;
  size?: number;
  countryId?: string;
}

export type ListRegionsInput_Filter = {
  query?: string;
  id?: ExpressionID[];
  countryId?: ExpressionID[];
  name?: ExpressionString[];
}

export type ListRegionsOutput = {
  items?: Region[];
  total?: number;
}

