// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Address = {
  country?: string;
  postCode?: string;
  region?: string;
  city?: string;
  line1?: string;
  line2?: string;
}

