// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Address = {
  firstName?: string;
  lastName?: string;
  companyName?: string;
  email?: string;
  phone?: string;
  country?: string;
  state?: string;
  city?: string;
  postcode?: string;
  streetName?: string;
  taxNumber?: string;
}

