// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Price } from "./price"

export type Invoice = {
  id?: string;
  number?: string;
  status?: string;
  customerId?: string;
  description?: string;
  fromInvoice?: Invoice_FromInvoice;
  createdAt?: string;
  dueAt?: string;
  hostedInvoiceUrl?: string;
  invoicePdfUrl?: string;
  currency?: string;
  amountDue?: number;
  amountPaid?: number;
  amountRemaining?: number;
  subtotal?: number;
  subtotalExcludingTax?: number;
  taxAmounts?: Invoice_TaxAmount[];
  tax?: number;
  discountAmounts?: Invoice_DiscountAmount[];
  total?: number;
  totalExcludingTax?: number;
  items?: Invoice_Item[];
}

export type Invoice_Item = {
  id?: string;
  description?: string;
  quantity?: number;
  price?: Price;
  currency?: string;
  amount?: number;
  amountExcludingTax?: number;
  unitAmountExcludingTax?: number;
  discountAmounts?: Invoice_DiscountAmount[];
  taxAmounts?: Invoice_TaxAmount[];
}

export type Invoice_TaxAmount = {
  amount?: number;
  inclusive?: boolean;
  taxRate?: string;
  taxabilityReason?: string;
  taxableAmount?: number;
}

export type Invoice_DiscountAmount = {
  amount?: number;
  discount?: string;
}

export type Invoice_FromInvoice = {
  relation?: string;
  invoice?: string;
}

