// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Address } from "./address"

export type Order = {
  id?: string;
  reference?: string;
  spaceId?: string;
  memberId?: string;
  userId?: string;
  createdAt?: string;
  expiresAt?: string;
  paidAt?: string;
  status?: string;
  recurrence?: string;
  billingAddress?: Address;
  currency?: string;
  subtotal?: number;
  taxAmount?: number;
  taxPercentage?: number;
  discountAmount?: number;
  discountPercentage?: number;
  grandTotal?: number;
  items?: Order_Item[];
}

export type Order_Item = {
  sku?: string;
  name?: string;
  description?: string;
  quantity?: number;
  itemPrice?: number;
  taxPercentage?: number;
  discountPercentage?: number;
  totalTaxAmount?: number;
  totalDiscountAmount?: number;
  totalPrice?: number;
}

