// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Address } from "./address"

export type Order = {
  id?: string;
  reference?: string;
  status?: string;
  items?: Order_Item[];
  billingAddress?: Address;
  shippingAddress?: Address;
  billingSameAsShipping?: boolean;
  estimatedShippingDate?: string;
  currency?: string;
  totalAmount?: number;
  shippingAmount?: number;
  discountAmount?: number;
  taxAmount?: number;
  taxRate?: number;
  taxNote?: string;
  grandTotal?: number;
  createdAt?: string;
  updatedAt?: string;
}

export type Order_Item = {
  id?: string;
  name?: string;
  imageUrl?: string;
  productId?: string;
  variantId?: string;
  quantityOrdered?: number;
  quantityCancelled?: number;
  quantityShipped?: number;
  quantityReturned?: number;
  quantityAllocated?: number;
  unitAmount?: number;
  totalAmount?: number;
  discountAmount?: number;
}

