// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Product, Product_Price } from "./product"

interface Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class ProductService {
  private readonly cli: Client;
  private readonly url: string;

  constructor(cli: Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }
}

export type CreateProductInput = {
  product?: Product;
}

export type CreateProductOutput = {
  productId?: string;
}

export type UpdateProductInput = {
  productId?: string;
  product?: Product;
}

export type UpdateProductOutput = Record<string, unknown>;

export type DescribeProductInput = {
  productId?: string;
}

export type DescribeProductOutput = {
  product?: Product;
}

export type DeleteProductInput = {
  productId?: string;
}

export type DeleteProductOutput = Record<string, unknown>;

export type ListProductPricesInput = {
  productId?: string;
}

export type ListProductPricesOutput = {
  items?: Product_Price[];
}

export type AddProductPriceInput = {
  productId?: string;
  price?: Product_Price;
  setDefault?: boolean;
}

export type AddProductPriceOutput = Record<string, unknown>;

export type RemoveProductPriceInput = {
  productId?: string;
  priceId?: string;
}

export type RemoveProductPriceOutput = Record<string, unknown>;

