// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Content } from "../ecm/content"

export type Product = {
  id?: string;
  name?: string;
  summary?: Content;
  description?: Content;
  images?: string[];
  outOfStock?: boolean;
  featured?: boolean;
  inactive?: boolean;
  backorder?: boolean;
  currency?: string;
  price?: number;
  regularPrice?: number;
  attributes?: Product_Attribute[];
  variants?: Product_Variant[];
  cursor?: string;
}

export type Product_Extra = Record<string, unknown>;

export type Product_Patch = Record<string, unknown>;

export type Product_Attribute = {
  key?: string;
  label?: string;
}

export type Product_Variant = {
  id?: string;
  name?: string;
  values?: Record<string, string>;
  images?: string[];
  outOfStock?: boolean;
  maxQuantity?: number;
  availableQuantity?: number;
}

export type Product_Translation = {
  id?: string;
  locale?: string;
  name?: string;
  summary?: Content;
  description?: Content;
  attributes?: Product_Attribute[];
}

