// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Address } from "./address"

export type ShoppingCart = {
  id?: string;
  items?: ShoppingCart_Item[];
  billingAddress?: Address;
  shippingAddress?: Address;
  billingSameAsShipping?: boolean;
  currency?: string;
  shippingMethodId?: string;
  totalAmount?: number;
  shippingAmount?: number;
  discountAmount?: number;
  taxAmount?: number;
  taxRate?: number;
  taxNote?: string;
  grandTotal?: number;
}

export type ShoppingCart_Item = {
  id?: string;
  productId?: string;
  variantId?: string;
  quantity?: number;
  unitAmount?: number;
  totalAmount?: number;
  discountAmount?: number;
}

