// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Node } from "../ecm/node"

export type Entry = {
  id?: string;
  type?: string;
  timestamp?: string;
  attributes?: Record<string, string>;
  attachments?: Entry_Attachment[];
  content?: Node;
}

export type Entry_Attachment = {
  rel?: string;
  type?: string;
  reference?: string;
}

