// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { ExpressionBool, ExpressionEnum, ExpressionID, ExpressionString } from "../wellknown/expression"
import { Term } from "./term"
import { Translation } from "./translation"
import { TranslationPair } from "./translation_pair"

interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class LocalizationService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  CreateTerm(input: CreateTermInput, opts?: any): Promise<CreateTermOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  ListTerms(input: ListTermsInput, opts?: any): Promise<ListTermsOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  UpdateTerm(input: UpdateTermInput, opts?: any): Promise<UpdateTermOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  RestoreTerm(input: RestoreTermInput, opts?: any): Promise<RestoreTermOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'')+"/restore";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  DeprecateTerm(input: DeprecateTermInput, opts?: any): Promise<DeprecateTermOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'')+"/deprecate";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  DeleteTerm(input: DeleteTermInput, opts?: any): Promise<DeleteTermOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  DescribeTerm(input: DescribeTermInput, opts?: any): Promise<DescribeTermOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ImportTerms(input: ImportTermsInput, opts?: any): Promise<ImportTermsOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  AddLocale(input: AddLocaleInput, opts?: any): Promise<AddLocaleOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/locales/"+encodeURIComponent(input.localeCode||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.localeCode);

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  RemoveLocale(input: RemoveLocaleInput, opts?: any): Promise<RemoveLocaleOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/locales/"+encodeURIComponent(input.localeCode||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.localeCode);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  ListLocales(input: ListLocalesInput, opts?: any): Promise<ListLocalesOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/locales";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  TranslateTerm(input: TranslateTermInput, opts?: any): Promise<TranslateTermOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'')+"/translations";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  ListTranslations(input: ListTranslationsInput, opts?: any): Promise<ListTranslationsOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'')+"/translations";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DeleteTranslation(input: DeleteTranslationInput, opts?: any): Promise<DeleteTranslationOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'')+"/translations/"+encodeURIComponent(input.translationId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);
    delete(input.translationId);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  SuggestTranslation(input: SuggestTranslationInput, opts?: any): Promise<SuggestTranslationOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'')+"/suggestions/"+encodeURIComponent(input.locale||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);
    delete(input.locale);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  UpdateTranslation(input: UpdateTranslationInput, opts?: any): Promise<UpdateTranslationOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'')+"/translations/"+encodeURIComponent(input.translationId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);
    delete(input.translationId);

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  ApproveTranslation(input: ApproveTranslationInput, opts?: any): Promise<ApproveTranslationOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'')+"/translations/"+encodeURIComponent(input.translationId||'')+"/approve";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);
    delete(input.translationId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  RejectTranslation(input: RejectTranslationInput, opts?: any): Promise<RejectTranslationOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/terms/"+encodeURIComponent(input.termId||'')+"/translations/"+encodeURIComponent(input.translationId||'')+"/reject";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.termId);
    delete(input.translationId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  ImportTranslations(input: ImportTranslationsInput, opts?: any): Promise<ImportTranslationsOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/translations/"+encodeURIComponent(input.locale||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.locale);

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  ExportTranslations(input: ExportTranslationsInput, opts?: any): Promise<ExportTranslationsOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/translations/"+encodeURIComponent(input.locale||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.locale);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListTranslationPairs(input: ListTranslationPairsInput, opts?: any): Promise<ListTranslationPairsOutput> {
    const path = "/projects/"+encodeURIComponent(input.projectId||'')+"/translate/"+encodeURIComponent(input.locale||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.projectId);
    delete(input.locale);

    return this.cli.call("GET", this.url+path, input, opts);
  }
}

export type CreateTermInput = {
  projectId?: string;
  term?: Term;
}

export type CreateTermOutput = {
  termId?: string;
}

export type ImportTermsInput = {
  projectId?: string;
  terms?: Term[];
}

export type ImportTermsOutput = {
  createdCount?: number;
  updatedCount?: number;
  deprecatedCount?: number;
}

export type ListTermsInput = {
  projectId?: string;
  offset?: number;
  size?: number;
  search?: string;
  filters?: ListTermsInput_Filter;
}

export type ListTermsInput_ExpressionTranslation = {
  locale?: string;
  status?: ExpressionEnum;
}

export type ListTermsInput_Filter = {
  query?: string;
  id?: ExpressionID[];
  key?: ExpressionString[];
  message?: ExpressionString[];
  status?: ExpressionEnum[];
  translation?: ListTermsInput_ExpressionTranslation[];
}

export type ListTermsOutput = {
  total?: number;
  items?: Term[];
}

export type UpdateTermInput = {
  projectId?: string;
  termId?: string;
  term?: Term;
}

export type UpdateTermOutput = Record<string, unknown>;

export type RestoreTermInput = {
  projectId?: string;
  termId?: string;
}

export type RestoreTermOutput = Record<string, unknown>;

export type DeprecateTermInput = {
  projectId?: string;
  termId?: string;
}

export type DeprecateTermOutput = Record<string, unknown>;

export type DeleteTermInput = {
  projectId?: string;
  termId?: string;
}

export type DeleteTermOutput = Record<string, unknown>;

export type DescribeTermInput = {
  projectId?: string;
  termId?: string;
}

export type DescribeTermOutput = {
  term?: Term;
}

export type AddLocaleInput = {
  projectId?: string;
  localeCode?: string;
}

export type AddLocaleOutput = Record<string, unknown>;

export type RemoveLocaleInput = {
  projectId?: string;
  localeCode?: string;
}

export type RemoveLocaleOutput = Record<string, unknown>;

export type ListLocalesInput = {
  projectId?: string;
  offset?: number;
  size?: number;
  filters?: ListLocalesInput_Filter;
}

export type ListLocalesInput_Filter = {
  code?: ExpressionID[];
  ready?: ExpressionBool[];
}

export type ListLocalesOutput = {
  total?: number;
  items?: ListLocalesOutput_Locale[];
}

export type ListLocalesOutput_Locale = {
  code?: string;
  ready?: boolean;
  translatedTerms?: number;
  missingTerms?: number;
  totalTerms?: number;
}

export type TranslateTermInput = {
  projectId?: string;
  termId?: string;
  translation?: Translation;
}

export type TranslateTermOutput = {
  translationId?: string;
}

export type ListTranslationsInput = {
  projectId?: string;
  termId?: string;
  offset?: number;
  size?: number;
  filters?: ListTranslationsInput_Filter;
}

export type ListTranslationsInput_Filter = {
  id?: ExpressionID[];
  message?: ExpressionString[];
  status?: ExpressionEnum[];
  locale?: ExpressionEnum[];
}

export type ListTranslationsOutput = {
  total?: number;
  items?: Translation[];
}

export type SuggestTranslationInput = {
  projectId?: string;
  termId?: string;
  locale?: string;
}

export type SuggestTranslationOutput = {
  messages?: string[];
}

export type UpdateTranslationInput = {
  projectId?: string;
  termId?: string;
  translationId?: string;
  translation?: Translation;
}

export type UpdateTranslationOutput = Record<string, unknown>;

export type ApproveTranslationInput = {
  projectId?: string;
  termId?: string;
  translationId?: string;
}

export type ApproveTranslationOutput = Record<string, unknown>;

export type RejectTranslationInput = {
  projectId?: string;
  termId?: string;
  translationId?: string;
}

export type RejectTranslationOutput = Record<string, unknown>;

export type DeleteTranslationInput = {
  projectId?: string;
  termId?: string;
  translationId?: string;
}

export type DeleteTranslationOutput = Record<string, unknown>;

export type DescribeTranslationInput = {
  projectId?: string;
  termId?: string;
}

export type DescribeTranslationOutput = {
  term?: Term;
}

export type ImportTranslationsInput = {
  projectId?: string;
  locale?: string;
  translations?: Record<string, string>;
}

export type ImportTranslationsOutput = {
  createdCount?: number;
}

export type ExportTranslationsInput = {
  projectId?: string;
  locale?: string;
}

export type ExportTranslationsOutput = {
  translations?: Record<string, string>;
}

export type ListTranslationPairsInput = {
  projectId?: string;
  locale?: string;
  source?: string;
  size?: number;
  offset?: number;
  after?: string;
  before?: string;
  search?: string;
  filters?: ListTranslationPairsInput_Filter;
}

export type ListTranslationPairsInput_Filter = {
  query?: string;
  termKey?: ExpressionString[];
  termStatus?: ExpressionEnum[];
  sourceMessage?: ExpressionString[];
  translationStatus?: ExpressionEnum[];
  translationMessage?: ExpressionString[];
}

export type ListTranslationPairsOutput = {
  total?: number;
  hasMore?: boolean;
  items?: TranslationPair[];
}

