// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Ticket, Ticket_Comment } from "./ticket"

export type TicketChangedEvent = {
  before?: Ticket;
  after?: Ticket;
}

export type CommentChangedEvent = {
  ticketId?: string;
  before?: Ticket_Comment;
  after?: Ticket_Comment;
}

