// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Document } from "./document"
import { Ticket, Ticket_Comment } from "./ticket"

export type DocumentCreatedEvent = {
  document?: Document;
}

export type DocumentUpdatedEvent = {
  document?: Document;
}

export type DocumentDeletedEvent = {
  document?: Document;
}

export type TicketChangedEvent = {
  before?: Ticket;
  after?: Ticket;
}

export type CommentChangedEvent = {
  before?: Ticket_Comment;
  after?: Ticket_Comment;
}

