"use strict";
// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.
Object.defineProperty(exports, "__esModule", { value: true });
exports.Helpdesk = void 0;
class Helpdesk {
    constructor(cli) {
        this.cli = cli;
    }
    DescribeDocument(input, opts) {
        return this.cli.call("eolymp.helpdesk.Helpdesk/DescribeDocument", input, opts);
    }
    ListDocuments(input, opts) {
        return this.cli.call("eolymp.helpdesk.Helpdesk/ListDocuments", input, opts);
    }
    CreateDocument(input, opts) {
        return this.cli.call("eolymp.helpdesk.Helpdesk/CreateDocument", input, opts);
    }
    UpdateDocument(input, opts) {
        return this.cli.call("eolymp.helpdesk.Helpdesk/UpdateDocument", input, opts);
    }
    DeleteDocument(input, opts) {
        return this.cli.call("eolymp.helpdesk.Helpdesk/DeleteDocument", input, opts);
    }
    DescribePath(input, opts) {
        return this.cli.call("eolymp.helpdesk.Helpdesk/DescribePath", input, opts);
    }
    ListPaths(input, opts) {
        return this.cli.call("eolymp.helpdesk.Helpdesk/ListPaths", input, opts);
    }
    ListParents(input, opts) {
        return this.cli.call("eolymp.helpdesk.Helpdesk/ListParents", input, opts);
    }
}
exports.Helpdesk = Helpdesk;
//# sourceMappingURL=helpdesk.js.map