// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Condition = {
  field?: string;
  logical?: Condition_Logical;
  string?: Condition_String;
  number?: Condition_Number;
  timestamp?: Condition_Timestamp;
  bool?: Condition_Bool;
  list?: Condition_List;
  empty?: Condition_Empty;
}

export type Condition_Logical = {
  operator?: string;
  children?: Condition[];
}

export type Condition_String = {
  operator?: string;
  value?: string;
  caseInsensitive?: boolean;
}

export type Condition_Number = {
  operator?: string;
  value?: number;
}

export type Condition_Timestamp = {
  operator?: string;
  value?: string;
}

export type Condition_Bool = {
  operator?: string;
  value?: boolean;
}

export type Condition_List = {
  operator?: string;
  value?: string[];
}

export type Condition_Empty = {
  value?: boolean;
}

