// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Log = {
  id?: string;
  ruleId?: string;
  trigger?: string;
  dryRun?: boolean;
  context?: Record<string, string>;
  messages?: Log_Message[];
  createdAt?: string;
}

export type Log_ToolCall = {
  id?: string;
  name?: string;
  status?: string;
  arguments?: string;
  result?: string;
  error?: string;
}

export type Log_Message = {
  id?: string;
  timestamp?: string;
  text?: string;
  toolCall?: Log_ToolCall;
}

