// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Policy = {
  id?: string;
  name?: string;
  principal?: string;
  principalId?: string;
  resource?: string;
  allowAll?: boolean;
  allows?: string[];
}

export type Policy_Patch = {
  name?: string;
  principal?: string;
  resource?: string;
  allowAll?: boolean;
  allows?: string[];
  disallow?: boolean;
}

