// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Principal = {
  id?: string;
  userId?: string;
  name?: string;
  role?: string;
  allows?: string[];
}

export type Principal_Patch = Record<string, unknown>;

