// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Scoreboard = {
  id?: string;
  slug?: string;
  name?: string;
  bestOf?: number;
  modes?: string[];
  contests?: Scoreboard_Contest[];
  attributes?: Scoreboard_Attribute[];
}

export type Scoreboard_Contest = {
  contestId?: string;
  index?: number;
  name?: string;
  imageUrl?: string;
  problems?: Scoreboard_Problem[];
}

export type Scoreboard_Problem = {
  problemId?: string;
  index?: number;
  title?: string;
}

export type Scoreboard_Attribute = {
  attributeKey?: string;
  index?: number;
  label?: string;
  type?: string;
}

export type Scoreboard_Patch = {
  slug?: string;
  name?: string;
  bestOf?: number;
}

export type Row = {
  memberId?: string;
  displayName?: string;
  index?: number;
  rank?: number;
  rankLength?: number;
  rankAll?: number;
  rankAllLength?: number;
  score?: number;
  penalty?: number;
  unofficial?: boolean;
  disqualified?: boolean;
  contests?: Row_ContestScore[];
  attributes?: Row_AttributeValue[];
}

export type Row_ProblemScore = {
  problemId?: string;
  score?: number;
  penalty?: number;
  percentage?: number;
  attempts?: number;
  time?: number;
  pending?: number;
  changed?: boolean;
  firstToSolve?: boolean;
}

export type Row_ContestScore = {
  contestId?: string;
  score?: number;
  penalty?: number;
  counted?: boolean;
  frozen?: boolean;
  problems?: Row_ProblemScore[];
}

export type Row_AttributeValue = {
  attributeKey?: string;
  string?: string;
  number?: number;
}

