// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { ExpressionBool, ExpressionID, ExpressionInt, ExpressionString } from "../wellknown/expression"
import { Row, Scoreboard, Scoreboard_Patch } from "./scoreboard"

interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class ScoreboardService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  CreateScoreboard(input: CreateScoreboardInput, opts?: any): Promise<CreateScoreboardOutput> {
    const path = "/scoreboards";

    return this.cli.call("POST", this.url+path, input, opts);
  }

  UpdateScoreboard(input: UpdateScoreboardInput, opts?: any): Promise<UpdateScoreboardOutput> {
    const path = "/scoreboards/"+encodeURIComponent(input.scoreboardId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.scoreboardId);

    return this.cli.call("PUT", this.url+path, input, opts);
  }

  DeleteScoreboard(input: DeleteScoreboardInput, opts?: any): Promise<DeleteScoreboardOutput> {
    const path = "/scoreboards/"+encodeURIComponent(input.scoreboardId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.scoreboardId);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  DescribeScoreboard(input: DescribeScoreboardInput, opts?: any): Promise<DescribeScoreboardOutput> {
    const path = "/scoreboards/"+encodeURIComponent(input.scoreboardId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.scoreboardId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListScoreboards(input: ListScoreboardsInput, opts?: any): Promise<ListScoreboardsOutput> {
    const path = "/scoreboards";

    return this.cli.call("GET", this.url+path, input, opts);
  }

  AddScoreboardContest(input: AddScoreboardContestInput, opts?: any): Promise<AddScoreboardContestOutput> {
    const path = "/scoreboards/"+encodeURIComponent(input.scoreboardId||'')+"/contests";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.scoreboardId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  RemoveScoreboardContest(input: RemoveScoreboardContestInput, opts?: any): Promise<RemoveScoreboardContestOutput> {
    const path = "/scoreboards/"+encodeURIComponent(input.scoreboardId||'')+"/contests/"+encodeURIComponent(input.contestId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.scoreboardId);
    delete(input.contestId);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  AddScoreboardAttribute(input: AddScoreboardAttributeInput, opts?: any): Promise<AddScoreboardAttributeOutput> {
    const path = "/scoreboards/"+encodeURIComponent(input.scoreboardId||'')+"/attributes";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.scoreboardId);

    return this.cli.call("POST", this.url+path, input, opts);
  }

  RemoveScoreboardAttribute(input: RemoveScoreboardAttributeInput, opts?: any): Promise<RemoveScoreboardAttributeOutput> {
    const path = "/scoreboards/"+encodeURIComponent(input.scoreboardId||'')+"/attributes/"+encodeURIComponent(input.attributeKey||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.scoreboardId);
    delete(input.attributeKey);

    return this.cli.call("DELETE", this.url+path, input, opts);
  }

  ListScoreboardRows(input: ListScoreboardRowsInput, opts?: any): Promise<ListScoreboardRowsOutput> {
    const path = "/scoreboards/"+encodeURIComponent(input.scoreboardId||'')+"/rows";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.scoreboardId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DescribeScoreboardRow(input: DescribeScoreboardRowInput, opts?: any): Promise<DescribeScoreboardRowOutput> {
    const path = "/scoreboards/"+encodeURIComponent(input.scoreboardId||'')+"/rows/"+encodeURIComponent(input.memberId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.scoreboardId);
    delete(input.memberId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  RebuildScoreboard(input: RebuildScoreboardInput, opts?: any): Promise<RebuildScoreboardOutput> {
    const path = "/scoreboards/"+encodeURIComponent(input.scoreboardId||'')+"/rebuild";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.scoreboardId);

    return this.cli.call("POST", this.url+path, input, opts);
  }
}

export type CreateScoreboardInput = {
  scoreboard?: Scoreboard;
}

export type CreateScoreboardOutput = {
  scoreboardId?: string;
}

export type UpdateScoreboardInput = {
  scoreboardId?: string;
  scoreboard?: Scoreboard_Patch;
}

export type UpdateScoreboardOutput = Record<string, unknown>;

export type DeleteScoreboardInput = {
  scoreboardId?: string;
}

export type DeleteScoreboardOutput = Record<string, unknown>;

export type DescribeScoreboardInput = {
  scoreboardId?: string;
}

export type DescribeScoreboardOutput = {
  scoreboard?: Scoreboard;
}

export type ListScoreboardsInput = {
  offset?: number;
  size?: number;
  search?: string;
  filters?: ListScoreboardsInput_Filter;
}

export type ListScoreboardsInput_Filter = {
  id?: ExpressionID[];
  slug?: ExpressionString[];
  contestId?: ExpressionID[];
}

export type ListScoreboardsOutput = {
  total?: number;
  items?: Scoreboard[];
}

export type AddScoreboardContestInput = {
  scoreboardId?: string;
  contestId?: string;
  index?: number;
}

export type AddScoreboardContestOutput = Record<string, unknown>;

export type RemoveScoreboardContestInput = {
  scoreboardId?: string;
  contestId?: string;
}

export type RemoveScoreboardContestOutput = Record<string, unknown>;

export type AddScoreboardAttributeInput = {
  scoreboardId?: string;
  attributeKey?: string;
  index?: number;
  label?: string;
}

export type AddScoreboardAttributeOutput = Record<string, unknown>;

export type RemoveScoreboardAttributeInput = {
  scoreboardId?: string;
  attributeKey?: string;
}

export type RemoveScoreboardAttributeOutput = Record<string, unknown>;

export type ListScoreboardRowsInput = {
  scoreboardId?: string;
  mode?: string;
  offset?: number;
  size?: number;
  filters?: ListScoreboardRowsInput_Filter;
  sortContestId?: string;
  order?: string;
  sortAttributeKey?: string;
}

export type ListScoreboardRowsInput_ExpressionAttribute = {
  attributeKey?: string;
  number?: ExpressionInt;
  string?: ExpressionString;
}

export type ListScoreboardRowsInput_Filter = {
  unofficial?: ExpressionBool[];
  disqualified?: ExpressionBool[];
  attributes?: ListScoreboardRowsInput_ExpressionAttribute[];
}

export type ListScoreboardRowsOutput = {
  total?: number;
  items?: Row[];
}

export type DescribeScoreboardRowInput = {
  scoreboardId?: string;
  memberId?: string;
  mode?: string;
}

export type DescribeScoreboardRowOutput = {
  row?: Row;
}

export type RebuildScoreboardInput = {
  scoreboardId?: string;
}

export type RebuildScoreboardOutput = {
  taskId?: string;
}

