// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Taxonomy = {
  year?: number;
  series?: string;
  scale?: string;
  difficulty?: number;
  country?: string;
  region?: string;
  city?: string;
}

