// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Runtime } from "../runtime/runtime"

export type Environment = {
  runtimes?: Runtime[];
}

