// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-eolymp for more details.


export type Contest = {
    id?: string;
    name?: string;
    type?: string;
    startsAt?: string;
    endsAt?: string;
    duration?: number;
    status?: string;
    public?: boolean;
    domain?: string;
}

