// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Score } from "./score"
import { Submission } from "./submission"

export type SubmissionCompletedEvent = {
  contestId?: string;
  submission?: Submission;
}

export type RebuildScoreEvent = {
  contestId?: string;
  activityId?: string;
}

export type ScoreChangedEvent = {
  contestId?: string;
  participantId?: string;
  unofficial?: boolean;
  score?: Score;
}

export type RetestProblemEvent = {
  contestId?: string;
  problemId?: string;
  activityId?: string;
}

