// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Contest } from "./contest"
import { Participant } from "./participant"
import { Score } from "./score"
import { Submission } from "./submission"

export type SubmissionCompletedEvent = {
  submission?: Submission;
}

export type RebuildScoreEvent = {
  contestId?: string;
  activityId?: string;
}

export type ScoreUpdatedEvent = {
  contestId?: string;
  participantId?: string;
  unofficial?: boolean;
  score?: Score;
}

export type ParticipantChangedEvent = {
  before?: Participant;
  after?: Participant;
}

export type ParticipantJoinedEvent = {
  contest?: Contest;
  participant?: Participant;
}

export type RetestProblemEvent = {
  contestId?: string;
  problemId?: string;
  activityId?: string;
}

