// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Participant = {
  id?: string;
  contestId?: string;
  memberId?: string;
  name?: string;
  unofficial?: boolean;
  status?: string;
  startedAt?: string;
  startedIn?: number;
  endAt?: string;
  endIn?: number;
  completeAt?: string;
  completeIn?: number;
  bonusTime?: number;
  passcode?: string;
  submits?: Participant_Submit[];
}

export type Participant_Submit = {
  problemId?: string;
  counter?: number;
}

