// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Problem = {
  id?: string;
  index?: number;
  score?: number;
  baseId?: string;
  contestId?: string;
  feedbackPolicy?: string;
  timeLimit?: number;
  memoryLimit?: number;
  fileSizeLimit?: number;
  submitLimit?: number;
}

export type Problem_Statement = {
  locale?: string;
  title?: string;
  content?: string;
  format?: string;
}

export type Problem_Test = {
  index?: number;
  example?: boolean;
  inputObjectId?: string;
  answerObjectId?: string;
  score?: number;
}

