// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Content } from "../ecm/content"

export type Reply = {
  id?: string;
  ern?: string;
  ticketId?: string;
  userId?: string;
  memberId?: string;
  message?: Content;
  createdAt?: string;
}

