// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { ExpressionBool } from "../wellknown/expression"
import { Scoreboard, Scoreboard_Row } from "./scoreboard"

interface _Client {
  call<R, E, O>(verb: string, url: string, args: R, opts?: any): Promise<E>;
}

export class ScoreboardService {
  private readonly cli: _Client;
  private readonly url: string;

  constructor(cli: _Client, url: string = 'https://api.eolymp.com') {
    this.cli = cli;
    this.url = url;
  }

  DescribeScoreboard(input: DescribeScoreboardInput, opts?: any): Promise<DescribeScoreboardOutput> {
    const path = "/contests/"+encodeURIComponent(input.contestId||'')+"/scoreboard";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.contestId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ListScoreboardRows(input: ListScoreboardRowsInput, opts?: any): Promise<ListScoreboardRowsOutput> {
    const path = "/contests/"+encodeURIComponent(input.contestId||'')+"/scoreboard/rows";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.contestId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  DescribeScoreboardRow(input: DescribeScoreboardRowInput, opts?: any): Promise<DescribeScoreboardRowOutput> {
    const path = "/contests/"+encodeURIComponent(input.contestId||'')+"/scoreboard/rows/"+encodeURIComponent(input.participantId||'');

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.contestId);
    delete(input.participantId);

    return this.cli.call("GET", this.url+path, input, opts);
  }

  ExportScoreboard(input: ExportScoreboardInput, opts?: any): Promise<ExportScoreboardOutput> {
    const path = "/contests/"+encodeURIComponent(input.contestId||'')+"/scoreboard/export";

    // Cleanup URL parameters to avoid any ambiguity
    delete(input.contestId);

    return this.cli.call("POST", this.url+path, input, opts);
  }
}

export type DescribeScoreboardInput = {
  contestId?: string;
}

export type DescribeScoreboardOutput = {
  scoreboard?: Scoreboard;
}

export type ListScoreboardRowsInput = {
  contestId?: string;
  mode?: string;
  size?: number;
  offset?: number;
  filters?: ListScoreboardRowsInput_Filter;
  sort?: string;
  order?: string;
}

export type ListScoreboardRowsInput_Filter = {
  unofficial?: ExpressionBool[];
  disqualified?: ExpressionBool[];
}

export type ListScoreboardRowsOutput = {
  total?: number;
  items?: Scoreboard_Row[];
}

export type DescribeScoreboardRowInput = {
  contestId?: string;
  participantId?: string;
  mode?: string;
}

export type DescribeScoreboardRowOutput = {
  row?: Scoreboard_Row;
}

export type ExportScoreboardInput = {
  contestId?: string;
  mode?: string;
}

export type ExportScoreboardOutput = {
  exportUrl?: string;
}

