// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { File } from "../executor/file"

export type Template = {
  id?: string;
  problemId?: string;
  runtime?: string;
  sourceUrl?: string;
  headerUrl?: string;
  footerUrl?: string;
  files?: File[];
}

