// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Violation = {
  id?: string;
  status?: string;
  type?: string;
  summary?: string;
  participantId?: string;
  submissionId?: string;
  createdBy?: string;
  createdAt?: string;
  confirmedBy?: string;
  confirmedAt?: string;
}

export type Violation_Patch = Record<string, unknown>;

