// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.

import { Content } from "../ecm/content"

export type Violation = {
  id?: string;
  status?: string;
  type?: string;
  summary?: Content;
  automatic?: boolean;
  participantId?: string;
  submissionId?: string;
  submissions?: string[];
  summaryText?: string;
  createdBy?: string;
  createdAt?: string;
  confirmedBy?: string;
  confirmedAt?: string;
}

export type Violation_Patch = Record<string, unknown>;

