// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Webhook = {
  id?: string;
  inactive?: boolean;
  link?: string;
  secret?: string;
  events?: string[];
}

