// Generated by the protocol buffer compiler. DO NOT EDIT!
// See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-js-esdk for more details.


export type Webhook = {
  id?: string;
  name?: string;
  secret?: string;
  endpoint?: string;
  inactive?: boolean;
  events?: string[];
  createdAt?: string;
  lastFailureAt?: string;
  lastSuccessAt?: string;
  deliveryCount?: number;
  failureCount?: number;
}

